source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'pg'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'pry-rails'

gem 'bcrypt-ruby', require: 'bcrypt'
gem 'figaro'
gem 'sendgrid'
gem 'paperclip'
gem 'aws-sdk'
gem 'token_phrase'
gem 'codemirror-rails'
gem 'backbone-on-rails'
gem 'rails-timeago', '~> 2.0'
gem 'jbuilder'
gem 'chosen-rails'
gem 'faker'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
end

group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'guard-rspec'
  gem 'shoulda-matchers'
end